---
deployment:
  tasks:
    - export DEPLOYPATH=/home7/sivip/public_html/sivip
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp * $DEPLOYPATH